spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 65602199533-fhsac0g9rol53al2dl1st3ao9pgrimsh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/auth/login/oauth2/code/google
            scope:
              - profile
              - email